config/routes.rb
PawOrClaw::Application.routes.draw do
  resources :pets

  resources :users

  root :to => 'landing_page#index'
  get "landing_page/index"

  

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :firstName, presence: true
	validates :lastName, presence: true
	validates :password, presence: true
	#validates :username, presence: true
	#emailFormatValidation = /[a-z\d.-]+@[a-z\d-.]+[.][a-z]+/i
	#validates :email, format: {with: emailFormatValidation}
	validates :email, presence: true
	validates :password, length: {minimum: 6}
	validates :password, confirmation: true
	validates :bio, length: {maximum: 150}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :bio, :rating, :up, :down, :user_id, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :bio, :password, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing_page/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="file:///Macintosh HD/Users/acole9/Documents/Penn2014/assets/ico/favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "bootstrap.min.css"%>

    <!-- Custom styles for this template -->
    <%= stylesheet_link_tag "jumbotron.css"%>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body id = "homepage">
	<div class="web-container">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- this link doesn't work-->
          <a class="navbar-brand" href="index.html.erb"><%= image_tag "logo.jpg", height: '50'%></a>
        </div>
        <div class="navbar-collapse collapse">
        <a href="signin.html">
        <div class="sign-up">
          	<p>Sign Up</p>
          </div>
          </a>
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
          
        </div><!--/.navbar-collapse -->
        
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div id="petinfo-container">
            <div class="petinfo">
                <p class="pinfo-name"> Boolean </p>
                <p class="rating above"> %65.7 </p>
                <p> This is a dog's bio. It is short and simple. </p>
                <p> #dog, #meowzer, #cute, #puppy, #love</p>
            </div>
        </div>
    <div class="jumbotron">
    	
      	<div class="pawclawbuttons">
        	<div id="pawbutton">
            	<button type="submit" id="paw"><%= image_tag "paw.png"%></button>
            </div> 
            
            <div id="clawbutton">
            	<button type="submit" id="claw"><%= image_tag "paw.png"%></button>
            </div> 
            <div id="welcome">
                	<h1>Welcome to Paw or Claw!</h1>
                    <p>Click PAW to upvote or CLAW to downvote</p>
            </div>
       </div>     
    </div>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> 
    </div><!-- /container -->
<!--	<div class="bottom">
        <div class="full-breadcrumb">
            <div class="breadcrumb">
                <p>About Us</p>
            </div>
            <div class="breadcrumb">
                <p>About Paw or Claw</p>
            </div>
     	</div>
     <div class="socialMedia">
        	<p>FB</p>
            <p>TW</p>
            <p>GM</p>   
     </div>
    </div>-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PawOrClaw</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :up %><br>
    <%= f.number_field :up %>
  </div>
  <div class="field">
    <%= f.label :down %><br>
    <%= f.number_field :down %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Rating</th>
      <th>Up</th>
      <th>Down</th>
      <th>User</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.bio %></td>
        <td><%= pet.rating %></td>
        <td><%= pet.up %></td>
        <td><%= pet.down %></td>
        <td><%= pet.user %></td>
        <td><%= pet.image %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @pet.bio %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @pet.rating %>
</p>

<p>
  <strong>Up:</strong>
  <%= @pet.up %>
</p>

<p>
  <strong>Down:</strong>
  <%= @pet.down %>
</p>

<p>
  <strong>User:</strong>
  <%= @pet.user %>
</p>

<p>
  <strong>Image:</strong>
  <%= @pet.image %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    First Name</br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    Last Name</br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    Email</br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    Username</br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    Password</br>
    <%= f.password_field :password %></br>
    Confirm Password</br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio, size: "25x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- settings-->
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!-- sign up-->
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- profile-->
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>